# -*- coding: utf-8 -*-
"""sesion_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n3gmTEhui773vQP1VzwgPZjy2HgXoSBN
"""

def saludo(nombre_de_usuario):
  print("hola",nombre_de_usuario)
    
n=input("Nombre de usuario ")
saludo(n)

2print("calcular el numero de combinaciones binominales \n" )
n=int(input("Numero de conjuntos : "))
m=int(input("Numero de elementos : "))
f=1
x=1
for i in range(1,n+1):
  f*=i

for j in range(1,m+1):
  x*=j
a=(n-m)
d=1
for k in range(1,a+1):
  d*=k
z=f/(x*d)
print("El numero de cominaciones que hay entre",n, "y ",m, "son", int(z))